### ISSUE TITLE
Refactor: Remove the override modifier when overriding an interface function

### ISSUE THREAD

**Issue by brotherlymite** [aave/aave-v3-core#779]
https://github.com/aave/aave-v3-core/blob/9630ab77a8ec77b39432ce0a4ff4816384fd4cbf/contracts/protocol/tokenization/base/DebtTokenBase.sol#L38

Post solidity version `0.8.8`, the `override` modifier is not required when overriding an interface function.
Since we are now on version `0.8.10`, maybe we can remove the `override` modifier to make the code cleaner/readable.

**Comment by miguelmtzinf** [comment]
@brotherlymite Thanks for raising this point! Although you are right, I'd reluctant to remove them because: i) it would increase the diff between codebase and deployed code, ii) there is no real benefit for end-users.

Also, I think letting the reader know a function is overriding an interface definition is a good thing (but this is controversial)

**Comment by miguelmtzinf** [comment]
Closing per comment above
