### ISSUE TITLE
repay with collateral quotes wrong numbers

### ISSUE THREAD

**Issue by blakelapierre** [aave/aave-v3-core#839]
Check the screenshots. 

The UI claimed the collateral after repay would be 12,430.95.

In fact, it was 12,428.21.

I've tried this with smaller and larger repay amounts and with different slippages and similar things happen.

This is on v3 Optimism.

![Screenshot from 2023-04-07 00-05-29](https://user-images.githubusercontent.com/777467/230547203-58015466-6177-4ab1-9f6b-4b90e8a640c6.png)

![Screenshot from 2023-04-07 00-32-40](https://user-images.githubusercontent.com/777467/230547485-b8a4f532-fe64-462f-ad83-626f529bfb01.png)

https://optimistic.etherscan.io/tx/0x35e0b43136dbfe36a1aa085bc5682d40142f01ad06ca196dc70c5639b0741dd6

The UI claimed 497.717... DAI would be used. It appears 500.46 was ultimately used. The difference is about 2.743.

2.743 / 500 = 0.5486%, above the 0.5% slippage
2.743 / 500.22 = 0.5483%, above the 0.5% slippage

Also, in this situation, as I increase the slippage tolerance, I get quoted ever lesser amounts of DAI that would be used to repay. However, I find that when I decided to go through with what looks like a pretty beneficial transaction, something like the opposite occurs and much larger amounts of DAI are used to repay.

![Screenshot from 2023-04-07 00-59-16](https://user-images.githubusercontent.com/777467/230550671-4ece68af-9f08-481b-b607-04e0a6b16479.png)
![Screenshot from 2023-04-07 00-59-08](https://user-images.githubusercontent.com/777467/230550672-390f8729-5dfc-41d3-a73b-c75ecf945bb5.png)
![Screenshot from 2023-04-07 00-59-02](https://user-images.githubusercontent.com/777467/230550673-2670ef39-ca8d-4483-9ba4-31075d34bc57.png)

**Comment by blakelapierre** [comment]
Ok, so I tried this again....

UI said 995 SUSD would be used.

Instead 1001 SUSD was used....

Is there a way to get my money back? What is going on here?

![Screenshot from 2023-04-27 05-17-57](https://user-images.githubusercontent.com/777467/234834647-01c78661-4126-4f25-81dc-5eaff2791b8f.png)

![Screenshot from 2023-04-27 05-19-29](https://user-images.githubusercontent.com/777467/234834676-7be3d24d-9695-4be4-9403-1f1cfd1b9321.png)

**Comment by miguelmtzinf** [comment]
Hey @blakelapierre ,
Sorry to see you are having a bad experience with the repay with collateral action.
I went through your [transaction](https://optimistic.etherscan.io/tx/0x35e0b43136dbfe36a1aa085bc5682d40142f01ad06ca196dc70c5639b0741dd6) and want to clarify: you are using `500.470349497893968460 aDAI` to repay `500 USDC debt`.
This seems reasonable to me since the UI was showing `497,71 aDAI` was going to be used with a `0.5% slippage`: `497.71 + 5% = 500.198`
There is a slight diff between `500.198` and `500.470` values that seems acceptable to me (there is a time delay between the moment you preview this result and your transaction get confirmed).
